name: devbox
description: The Developer Toolbox

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  go_router: ^7.1.1
  window_manager: ^0.3.4
  flutter_hooks: ^0.18.6
  hooks_riverpod: ^2.3.6
  riverpod_annotation: ^2.1.1
  shared_preferences: ^2.1.1
  package_info_plus: ^4.0.2
  flutter_code_editor: ^0.2.9
  easy_localization: ^3.0.2
  flutter_highlight: ^0.7.0
  highlight: ^0.7.0
  flutter_acrylic: ^1.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.13.1
  go_router_builder: ^2.0.2
  build_runner: ^2.4.4
  build_verify: ^3.1.0
  riverpod_generator: ^2.0.0

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/translations/